### ISSUE TITLE
Training steps per subject

### ISSUE THREAD

**Issue by shadow2496** [forchchch/DisenBooth#1]
Hi, I'm trying to reproduce the paper results, and it seems different training steps are used for each subject.
Could you share the training steps of the subjects from DreamBench?

**Comment by forchchch** [comment]
Yes, different subjects need different steps because of the priors of the Stable Diffusion. I am sorry that this work was finished half a year ago and I also forgot the detailed training steps for each subject. However, in my  memory, subjects like animals(dog, cat, teddy bear, candle) need fewer steps about 1000. Subjects like backpack and can need about 2000 steps. Similarly, in our evaluation, we also choose the best steps with few evaluation data for all the fine-tuning methods for fair comparison. Generally, DisenBooth needs more steps than dream booth because it less overfits the identity-irrelevant information.
