### ISSUE TITLE
Subject token

### ISSUE THREAD

**Issue by AIshutin** [forchchch/DisenBooth#3]
Hi! 

Could you please explain to me which prompts did you use? 
Specifically,
1. You don't use "a photo of" prefix, do you?
2. Do you use prompts like "a $class\</w> $class" for every subject?

In paper you wrote:
![image](https://github.com/forchchch/DisenBooth/assets/30271345/d2c1ff50-42e6-4979-99d0-befc14d2fc61)

In the script you use: "a dog\</w> dog". This actually is tokenized as:
```python
['a</w>', 'dog</w>', '</</w>', 'w</w>', '></w>', 'dog</w>']
```
Thus, "dog\</w>" is a common token if I understand correctly.

**Comment by forchchch** [comment]
1. We do not use the prefix. 
2. For subject-driven text-to-image generation, using a rare token like 'sks' or a common token 'dog</w>' achieve similar results. Using a related token(like 'dog</w>') to the subject will achieve better disentanglement easily, because it is naturally related to the subject and will make the identity-relevant branch more focus on the subject information.

**Comment by AIshutin** [comment]
Sorry to bother you, but I wish to once again clarify something. By 'dog' in your comment do you mean 'dog' (tokenized as 'dog\<\w>') or 'dog<\w>' (tokenized as  'dog\</w>', '</</w>', 'w\</w>', '>\</w>')? 
(*Github UI hides '\</w>' if written w/o slash.*)

**Comment by forchchch** [comment]
dog<\/w>

**Comment by AIshutin** [comment]
Thanks
